import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  scenarios: {
    smoke: {
      executor: 'constant-vus',
      vus: 20,
      duration: '2m',
    },
  },
  thresholds: {
    http_req_failed: ['rate<0.001'],
    http_req_duration: ['p(95)<300'],
  },
};

const BASE_URL = __ENV.BASE_URL || 'http://localhost:8000';
const EMAIL = __ENV.TEST_EMAIL || 'loadtest@example.com';
const PASSWORD = __ENV.TEST_PASSWORD || 'loadtest-password';

function login() {
  const body = {
    username: EMAIL,
    password: PASSWORD,
    grant_type: 'password',
  };

  const response = http.post(
    `${BASE_URL}/api/v2/users/access-token`,
    body,
    {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    }
  );

  check(response, {
    'login status is 200': (r) => r.status === 200,
  });

  const payload = response.json();
  return payload && payload.data ? payload.data.access_token : null;
}

export default function () {
  const token = login();
  if (!token) {
    sleep(1);
    return;
  }

  const headers = { Authorization: `Bearer ${token}` };

  const meResponse = http.get(`${BASE_URL}/api/v2/users/me`, { headers });
  check(meResponse, { 'me status is 200': (r) => r.status === 200 });

  const listResponse = http.get(`${BASE_URL}/api/v2/items/list?limit=20`, { headers });
  check(listResponse, { 'list status is 200': (r) => r.status === 200 });

  const createResponse = http.post(
    `${BASE_URL}/api/v2/items/obj`,
    JSON.stringify({ title: 'load-item', description: 'generated by k6' }),
    { headers: { ...headers, 'Content-Type': 'application/json' } }
  );
  check(createResponse, { 'create status is 201': (r) => r.status === 201 });

  sleep(0.2);
}
